name: Production Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy-to-render:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './backend'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Backend Image'
        run: |
          docker build . --tag ghcr.io/haudacia/surflow:${{ github.sha }}
          docker push ghcr.io/haudacia/surflow:${{ github.sha }}

      - name: Install and configure the Render CLI
        run: |
          curl -sSL https://cli.render.com/install | bash
          echo "export PATH=\$PATH:/root/.render/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Update image in Render
        run: render deploy --image ghcr.io/haudacia/surflow:${{ github.sha }} --service surflow-proposed-ira

      - name: Redeploy service in Render
        run: render redeploy surflow-proposed-ira
